import Head from 'next/head'
import { Heading } from '@chakra-ui/react'
import { Box } from '@chakra-ui/react'
import Header from '../components/Header'
import SlideShow from '../components/SlideShow'
import Pledges from '../components/Pledges'
import Classes from '../components/Classes'
import Programs from '../components/Programs'

export default function Home() {
  return (
    <>
      <Head>
        <title>Adroitz Coding School</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Header/>
        <SlideShow/>
        <Classes/>
        <Programs/>
        <Pledges/>
       
        
      <Heading>
        Welcome to Adroitz coding school for kids
      </Heading>
      </Box>
     
    </>
  )
}
